### ISSUE TITLE
java.lang.IllegalStateException: KoinApplication has not been started

### ISSUE THREAD

**Issue by sboishtyan** [holgerbrandl/kalasim#14]
kalasim 0.6.6

```
fun main() {
    val devices = Resource(name = "devices", capacity = 1)
}
```

```
Exception in thread "main" java.lang.IllegalStateException: KoinApplication has not been started
	at org.koin.core.context.GlobalContext.get(GlobalContext.kt:35)
	at org.kalasim.Resource.<init>(Resource.kt:42)
	at MainKt.main(Main.kt:7)
	at MainKt.main(Main.kt)
```

How could I start `KoinApplication`?

**Comment by holgerbrandl** [comment]
You would need to create a simulation context before instantiating the resource. E.g. with

```kotlin
Environment().apply{
  val devices = Resource(name = "devices", capacity = 1)
}
```

For more details regarding koin and dependency injection see https://www.kalasim.org/basics/#dependency-injection

Feel welcome if you have further issues.

**Comment by holgerbrandl** [comment]
I've adjusted the docs accordingly

**Comment by DeveloperMobilePersonal** [comment]
`fun ComponentActivity.contextAwareActivityScope() = runCatching {
    LifecycleScopeDelegate<Activity>(
        lifecycleOwner = this,
        koin = getKoin(this)
    )
}.getOrElse { activityScope() }`

`private fun getKoin(activity: ComponentActivity): Koin {
    return if (activity is KoinComponent) {
        activity.getKoin()
    } else {
        GlobalContext.getOrNull() ?: startKoin {
            androidContext(activity.applicationContext)
            modules(listModule)
        }.koin
    }
}`
### Here's my fix, give it a try!
