### ISSUE TITLE
Dark mode documentation

### ISSUE THREAD

**Issue by aSemy** [holgerbrandl/kalasim#63]
Please could docs be updated to include a dark-mode toggle? :)

This should be pretty easy with mkdocs, see these PRs for inspiration:

* https://github.com/cashapp/sqldelight/pull/3637
* https://github.com/square/okio/pull/1174

I'm willing to make a PR, if you'd like

**Comment by aSemy** [comment]
P.S. it would be nice to add the documentation URL on the GitHub About section 

<img width="403" alt="image" src="https://user-images.githubusercontent.com/897017/232936019-e6b31a0b-6dfa-4553-b7c5-2eddbe36d277.png">

**Comment by holgerbrandl** [comment]
Oh "these" dark mode people. :-) Thanks for the suggestion. The links contrast when using dark mode now, lack a bit of contrast in my taste, but I guess it's fine for now.

I've adjusted the link as well.

**Comment by aSemy** [comment]
Wonderful, thank you on behalf of the dark mode people! :)

Yes, the link contrast is very low... It looks like it might be this issue https://github.com/squidfunk/mkdocs-material/issues/4600? Although it does look like kalasim is using the latest versions of Mkdocs and Mkdocs Material... but I'm not very familiar with Mkdocs or Python.

**Comment by holgerbrandl** [comment]
Not sure how to indicate a more recent version in https://github.com/holgerbrandl/kalasim/blob/master/.github/workflows/manual.yml
The mkdocs version comes along somehow via the github action system.
